# Default values for chaosblade.

# chaosblade-operator
operator:
  repository: chaosbladeio/chaosblade-operator
  #    repository: "registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-operator"
  version: 0.7.0
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent

blade:
  repository: chaosbladeio/chaosblade-tool
#  repository: registry-vpc.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-tool

env:
  logLevel: info

webhook:
  enable: true