# Default values for chaosblade.

# chaosblade-operator
operator:
  repository: chaosbladeio/chaosblade-operator
  version: 0.7.0
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent

blade:
  repository: chaosbladeio/chaosblade-tool
  version: 0.7.0
  pullPolicy: IfNotPresent

env:
  logLevel: info

webhook:
  enable: true

daemonset:
  enable: true