# Default values for chaosblade.
# chaosblade-operator
operator:
  repository: "registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-operator"
  version: 0.6.0
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent

# chaosblade-tool
blade:
  repository: registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-tool
  version: 0.6.0
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent

env:
  zapLevel: ""

webhook:
  enable: true